### ISSUE TITLE
[BUG] Google Chrome only - repeat opening of THE SAME panel calculates contentSize incorrectly.

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#12]
Hello,

Here's the [codepen link](http://codepen.io/tmrczk/pen/dXRYky).

On first page load panel looks like this:

![image](https://cloud.githubusercontent.com/assets/3987203/16546865/08954950-4127-11e6-8727-cde4fb9f9d3d.png)

Now, close it using "X" button and it will reopen itself and will look like this:

![image](https://cloud.githubusercontent.com/assets/3987203/16546878/2cf37ae2-4127-11e6-933d-2baf65099442.png)

Can this be fixed, please? :-)

Thank you!

**Comment by Flyer53** [comment]
Hi again ...
I don't think this is a jsPanel bug. Using <code>contentSize: "auto auto"</code> you will have different results in different browsers because you can't realy predict how the browser in question calculates necessary dimensions. In your example above (the complete codepen example) you could simply remove option.contentOverflow in order not  to have scrollbars -> then it works great.

**Or if you want to keep the scrollbars** don't use option.contentSize at all and add a callback that does the autosizing like:

``` javascript
var panel = null;
function openIt() {
  panel = $.jsPanel({
    /* added callback ---------------------------------------- */
    callback: function(panel) {
      panel.resize("auto", "auto").reposition();
    },
    /* ------------------------------------------------------- */
    id: 'evaluation',
    headerTitle: 'Result',
    theme: 'bootstrap-success',
    contentOverflow: 'scroll',
    onclosed: function() {
      openIt();
    },
    content: function(a, b) {

      str = '<pre>var panelContents = "String that arrived via AJAX Call";\n'+
        'var Panel = $.jsPanel({\n'+
        '    id: "awesomeJsPanel",\n'+
        '    headerTitle: "My Header",\n'+
        '    contentSize: "auto auto",\n'+
        '    content: function(a, b) {\n'+
        '        // Some post-processing here...\n'+
        '        return panelContents;\n'+
        '    }'+
        '});</pre>';

      return str;
    }
  });
}

openIt();
```

But consider that when you get the panel content with an ajax request you need to put <code>panel.resize("auto", "auto").reposition();</code> in the done callback of the ajax call in order to ensure that the resizing is done when the content is actually there.
http://jspanel.de/api/#option/contentSize has an example for this at the very bottom

**Comment by temuri416** [comment]
Hello,

I understand what you are saying and your recommendations do work. The only reason I opened this ticket is that Chrome DOES get the auto-size right on FIRST attempt. Something's happening the second time panel opens.

But, that's probably a small thing :)

Thanks.

P.S. Actually, `panel.resize("auto", "auto").reposition();` did exactly what I needed!
