### ISSUE TITLE
[QUESTION/NFR] Ability to reuse DOM element as source for content

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#15]
Hi Stefan,

Got a question/suggestion.. I'm trying to use `$('#myModalContent')` as the source for jsPanel's content.

But if that panel has Close button enabled and gets closed, there's no way to reopen the modal as source DOM element no longer exists.
1. What approach would you recommend if I want to point to DOM element for source?
2. Would it be possible for jsPanel to always clone original DOM so it's available to subsequent open calls?

Thank you!

**Comment by Flyer53** [comment]
Hey there,

did you ever take a look at jQuery's **.clone()** method?

http://api.jquery.com/clone/

On first sight it seems to be exactly what you need.

**Comment by temuri416** [comment]
Hi,

I think you misunderstood me. It is jsPanel that should clone source element. Once I initialize jsPanel - my source DOM element has disappeared.

**Comment by Flyer53** [comment]
Mmmmh, what I understood is ...

You have some content already in the document you want to clone in order to append the clone to the content section of a jsPanel yet to create. The original content will remain at its place (and thus usable again) because only the clone is appended to the panel.

For this scenario I created an example using jQuery's **.clone()** method within the api docs of option.content. Take a look at example 5
**http://jspanel.de/api/#option/content**

**Comment by temuri416** [comment]
Oh.. Now I see what you meant by me using **.clone()**! Thank you, I did not realize that trick would work.
