### ISSUE TITLE
FullScreen panel in IE11 has extra margin / padding on the right

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel3#23]
You can tell i just started testing my app in IE :)

It seems that panels have a wider margin/padding on the right hand size in IE11 when in full screen mode.

I tried it on a few of your demos and they all did the same.

Thanks

**Comment by Flyer53** [comment]
Yes. The right margin is to make room for a possible crollbar. Otherwise IE would extend the panel so far right that it slips under the scrollbar hiding the close control for example.
I'm not very happy with this either, but so far I couldn't find a reliable way to detect the presence of a scrollbar in IE or to get IE window.width without the scrollbar.

**Comment by whittssg** [comment]
Ah ok.. Makes sense - not a major issue anyway. Thanks

**Comment by Flyer53** [comment]
Searched this topic again and will make a change in the next update:
The real problem behind this is that IE autohides the scrollbar, and, when showing the scrollbar just overlays the page content.
In the next update I'll add

``` javascript
$('body').css('-ms-overflow-style', 'scrollbar');
```

which will make IE render the scrollbar as other browsers do and not as overlay.... and everything is fine.
Of course I'll have to document this somewhere.
