### ISSUE TITLE
autoposition Issue

### ISSUE THREAD

**Issue by KhaledSMQ** [Flyer53/jsPanel3#35]
@Flyer53 @pvnr0082t   Hi, first of all thank you for the amazing Panel ever i saw.

I have spend more than 4 hours figure out problem i face in jsPanel 3.5
the actual problem if i have more than 3 panels and all of them in **minimized** status then i open any one of them (**normalize**)  and close it, the actual HTML elements not deleted from the page and the other hidden jsPanel's elements its appear, then i notice ``` autoposition: true```  in the configuration makes this problem.

i don't know if i miss any configurations or it's a bug in the code. any way at the moment commented  autoposition option

```
 position: {
                                my: showPostion + '-top',
                                at: showPostion + '-top',
                                of: '#main_map_layer',
                                modify: true,
                                fixed: 'true',
                                // autoposition: true
                            },
```

**Comment by Flyer53** [comment]
Hi Khaled,
thanks a lot for the praise :)
Yes, there is an issue. But ... 
The positioning parameter `autoposition` is intended for use together with the paneltype "hint" (that piece of info is missing in the docs ... my fault). Hints are not supposed to be minimized since they close after a specified time anyhow. And when closed the other hints reposition automatically. That's why they reappear in your usecase without removing the minimized replacement because the script doesn't check for minimized panels of type "hint".

However:
2 more things to mention regarding your code above:

- the position parameter `modify`, if used, needs to be a function. Setting it to `true` doesn't have an effect.
- ´the position parameter `autoposition`, if used, must be one of the strings `"DOWN"`, `"RIGHT"`, `"UP"` or `"LEFT"` (note all letters written in upper case). Setting it simply to `true` is not a valid setting.

option.position docs: http://jspanel.de/api/#option/position

If you tell me a bit more about your usecase and what you expect the panels to do I might be able to give you some more tips.

Hope I could help ...

Regards, Stefan

**Comment by KhaledSMQ** [comment]
Hi @Flyer53, 

Thank you for replay, thats is pretty interesting and i fully understand the case. Thank you again for explaining.
Regarding my case actully i am working on a point of sales for ticketing system and jsPanel was the magic solution for me to make an multiple orders in hold before confirming

![screen shot 2017-01-20 at 11 29 14 pm 1](https://cloud.githubusercontent.com/assets/8835798/22162570/aa980424-df68-11e6-941f-49f7225915e3.png)

**Comment by Flyer53** [comment]
Looks real good :)
Is there anything more I can do to help you?

**Comment by KhaledSMQ** [comment]
Thank you so much i think i am just fine, i have one more thing that might also help regarding headerToolbar when using bootstrap```bootstrap-info and others colors``` theme there is an issue  the toolbar is not appear correctly, i just added in callback ```$('.panel-heading', this).css({height: 'auto'});``` and it solve the problem

**Comment by Flyer53** [comment]
Well, depending on the framework you use (bootstrap 3 or 4, foundation, ...) there might be the one or the other small issue to tweak a bit.

Btw: I'm experimenting with a jsPanel version free of dependencies (not even jQuery). My test version is coming along nicely, but requires a quite recent browser: FF50, Chrome54, Edge14.

You can find a simple demo page here: http://alpha.jspanel.de/media/demos/nojquery/index.php
